### ISSUE TITLE
Card question

### ISSUE THREAD

**Issue by zoopster** [dotKrad/hass-fpl#32]
First...thank you, thank you, thank you. I'd buy you a pony if I knew where to send it!
This integration works perfectly...BUT.

You had posted the yaml for a card you use and for the life of me (and I really suck at HASS cards) I cannot get it to show correctly. I'm thinking its simply what entities I'm using. 

So...the question is what entity goes where???

```
cards:
  - card:
      entities:
        - attribute: as_of_days          
          entity: sensor.fpl_*****
          entity_row: true
          max: '${ vars[0] }'
          name: Days
          positions:
            icon: 'off'
            indicator: 'off'
            minmax: inside
            title: inside
            value: inside
          severity:
            - color: Green
              from: 0
              to: '${ vars[0] * 0.5 }'
            - color: Yellow
              from: '${ vars[0] * 0.5 + 1}'
              to: '${ vars[0] * 0.80 }'
            - color: Red
              from: '${ vars[0] * 0.80 + 1}'
              to: '${ vars[0] }'
          style: 'ha-card{border-radius: 0;}'
          type: 'custom:bar-card'
      title: FPL
      type: entities
    entities:
      - sensor.fpl_*****
    type: 'custom:config-template-card'
    variables:
      - 'states[''sensor.fpl_*****''].attributes.service_days'
  - attribute: projected_bill
    entity: sensor.fpl_*****
    name: Projected Bill
    type: entity
type: 'custom:vertical-stack-in-card'
```

Thanks!!!
