### ISSUE TITLE
No longer getting total usage?

### ISSUE THREAD

**Issue by MACscr** [dotKrad/hass-fpl#5]
Seems after the resent changes, there is no longer any total usage tracking for the billing cycle? Is that the case?

**Comment by dotKrad** [comment]
Fpl changed the way it expose data, Im working on it

**Comment by MACscr** [comment]
No problem. Sure wish they provided an api and also access to the bidgely data.

**Comment by dotKrad** [comment]
they don't provide an Api, I'm using the api they are using with the web
app, kind of reverse engineering

**Comment by MACscr** [comment]
Completely understand. Thats why I said i WISHED they had an api. =P

**Comment by MACscr** [comment]
I ended up creating a custom sensor template using the daily usage total:

```
      fpl_total_power_usage:
        friendly_name: "Total Power Usage"
        value_template: "{{ state_attr('sensor.fpl_1034853430','daily_usage') | sum(attribute='usage') }}"
        unit_of_measurement: kWh
```
