### ISSUE TITLE
Missing Card Examples

### ISSUE THREAD

**Issue by dorgan** [dotKrad/hass-fpl#7]
I see the following card examples for Lovelace UI (https://community.home-assistant.io/t/add-fpl-api-to-home-assistant/78347), but it seems that some of these components no longer exist, nor can I get the variables to work.

Here is what I have, but I have not been able to get service days into a variable:
```
type: vertical-stack
cards:
  - attribute: as_of_days
    name: Days
    positions:
      icon: 'off'
      indicator: 'on'
      minmax: 'on'
      title: inside
      value: inside
    severity:
      - color: Green
        from: 0
        to: 15
      - color: Yellow
        from: 16
        to: 25
      - color: Red
        from: 26
        to: 31
    type: 'custom:bar-card'
    entities:
      - entity: sensor.fpl_***
    variables:
      - 'states[''sensor.fpl_***''].attributes.service_days'
    title: FPL
    direction: right
    min: 1
    max: 31
    animation:
      state: 'on'
      speed: '5'
  - type: entities
    entities:
      - entity: sensor.fpl_bill_to_date
      - entity: sensor.fpl_daily_avg
      - entity: sensor.fpl_projected_bill
      - entity: sensor.fpl_total_power
      - entity: sensor.fpl_service_days
    state_color: false
layout:
  key: 16950a26-4149-4254-88dc-33438177d1b7
```
